# simple docker build for development
FROM golang:1.19

# nake a app dir, its not necessary but its good practice
WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download


CMD air